project_id = "twrzhnoboxbxmmcrgwmj"

[functions.create-checkout]
verify_jwt = false

[functions.create-sell-order]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false

[functions.send-order-notification]
verify_jwt = false

[functions.send-marketing-email]
verify_jwt = false
